<?php
/**
 * @category   Amrendra
 * @package    Amrendra_CustomCatalog
 * @author     sachin.bluethink@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Amrendra\CustomCatalog\Controller\Adminhtml\Items;

class Edit extends \Amrendra\CustomCatalog\Controller\Adminhtml\Items
{

    public function execute()
    {
        $id = $this->getRequest()->getParam('id');
        
        $catalog_model = $this->_objectManager->create('Amrendra\CustomCatalog\Model\CustomCatalog');

        if ($id) {
            $catalog_model->load($id);
            if (!$catalog_model->getId()) {
                $this->messageManager->addError(__('This Catalog no longer exists.'));
                $this->_redirect('amrendra_customcatalog/*');
                return;
            }
        }
        // set entered data if was error when we do save
        $data = $this->_objectManager->get('Magento\Backend\Model\Session')->getPageData(true);
        if (!empty($data)) {
            $catalog_model->addData($data);
        }
        $this->_coreRegistry->register('current_amrendra_customcatalog_items', $catalog_model);
        $this->_initAction();
        $this->_view->getLayout()->getBlock('items_items_edit');
        $this->_view->renderLayout();
    }
}
