<?php
/**
 * @category   Amrendra
 * @package    Amrendra_CustomCatalog
 * @author     sachin.bluethink@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Amrendra\CustomCatalog\Controller\Adminhtml\Items;

class Index extends \Amrendra\CustomCatalog\Controller\Adminhtml\Items
{
    /**
     * Items list.
     *
     * @return \Magento\Backend\Model\View\Result\Page
     */
    public function execute()
    {
        /** @var \Magento\Backend\Model\View\Result\Page $resultPage */
        $resultPage = $this->resultPageFactory->create();
        $resultPage->setActiveMenu('Amrendra_CustomCatalog::test');
        $resultPage->getConfig()->getTitle()->prepend(__('Custom Catalog'));
        $resultPage->addBreadcrumb(__('CustomCatalog'), __('CustomCatalog'));
        $resultPage->addBreadcrumb(__('CustomCatalog'), __('CustomCatalog'));
        return $resultPage;
    }
}